
name: Build
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 0"

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: explode
              run: echo explode