
name: Build
on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 0"

env:
    GH_TOKEN: ${{ github.token }}
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"
            
            - name: Clone build script
              run: git clone --depth 1 --branch main https://github.com/VendroidEnhanced/plugin .
    
            - name: Run build script (Vencord)
              run: node index.mjs vencord